#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file defines additional (traditional, simplified, pinyin) tuples that
# won't be added to CC-CEDICT because they consist of multiple parts that have
# their own dictionary entries. By adding them here, mistakes by the
# prefix-matching tokenizer can be fixed on a case-by-case basis.
# To allow corrections to the pinyin, no additional syllable-joining step will
# be performed.
override = [
    ('不是', '不是', 'bu4 shi4'),
    ('不了', '不了', 'bu5liao3'),
    ('不過', '不过', 'bu4guo4'),
    ('中的', '中的', 'zhong1 de5'),
    ('都會', '都会', 'dou1 hui4'),
    ('穿著', '穿着', 'chuan1 zhe5'),
    ('一隻', '一只', 'yi1 zhi1'),
    ('兩隻', '两只', 'liang3 zhi1'),
    ('三隻', '三只', 'san1 zhi1'),
    ('四隻', '四只', 'si4 zhi1'),
    ('五隻', '五只', 'wu3 zhi1'),
    ('六隻', '六只', 'liu4 zhi1'),
    ('七隻', '七只', 'qi1 zhi1'),
    ('八隻', '八只', 'ba1 zhi1'),
    ('九隻', '九只', 'jiu3 zhi1'),
    ('十隻', '十只', 'shi2 zhi1'),
    ('幾隻', '几只', 'ji3 zhi1'),
    ('什麼', '什么', 'shen2me5'),
    ('甚麼', '什么', 'shen2me5'),
    ('甚麽', '什么', 'shen2me5'),
    ('到了', '到了', 'dao4 le5'),
    ('打網球', '打网球', 'da3 wang3qiu2'),
    ('這就', '这就', 'zhe4 jiu4'),
    ('這不', '这不', 'zhe4 bu4'),
    ('是日本', '是日本', 'shi4 Ri4ben3'),
    ('是日本人', '是日本人', 'shi4 Ri4ben3ren2'),
    ('說法語', '说法语', 'shuo1 Fa3yu3'),
    ('本字典', '本字典', 'ben3 zi4dian3'),
    ('家公司', '家公司', 'jia1 gong1si1'),
    ('是非常', '是非常', 'shi4 fei1chang2'),
    ('有時間', '有时间', 'you3 shi2jian1'),
    ('十分鐘', '十分钟', 'shi2 fen1zhong1'),
    ('幾分鐘', '几分钟', 'ji3 fen1zhong1'),
    ('小女孩', '小女孩', 'xiao2 nv3hai2'),
    ('的姐姐', '的姐姐', 'de5 jie3jie5'),
    ('費時間', '费时间', 'fei4 shi2jian1'),
    ('的哥哥', '的哥哥', 'de5 ge1ge5'),
    ('多時間', '多时间', 'duo1 shi2jian1'),
    ('下週日', '下周日', 'xia4 Zhou1ri4'),
    ('個兒子', '个儿子', 'ge4 er2zi5'),
    ('我去年', '我去年', 'wo3 qu4nian2'),
    ('人相信', '人相信', 'ren2 xiang1xin4'),
    ('早起床', '早起床', 'zao3 qi3chuang2'),
    ('在下一站', '在下一站', 'zai4 xia4yi1zhan4'),
    ('點出發', '点出发', 'dian3 chu1fa1'),
    ('是故意', '是故意', 'shi4 gu4yi4'),
    ('所知道', '所知道', 'suo3 zhi1dao4'),
    ('在地上', '在地上', 'zai4 di4shang4'),
    ('做作業', '做作业', 'zuo4 zuo4ye4'),
    ('在前面', '在前面', 'zai4 qian2mian4'),
    ('幾點鐘', '几点钟', 'ji3 dian3zhong1'),
    ('上火車', '上火车', 'shang4 huo3che1'),
    ('多事情', '多事情', 'duo1 shi4qing5'),
    ('本應該', '本应该', 'ben3 ying1gai1'),
    ('有成功', '有成功', 'you3 cheng2gong1'),
    ('說中文', '说中文', 'shuo1 Zhong1wen2'),
    ('在下雪', '在下雪', 'zai4 xia4xue3'),
    ('在下雨', '在下雨', 'zai4 xiayu3'),
    ('吃水果', '吃水果', 'chi1 shui3guo3'),
    ('門外語', '门外语', 'men2 wai4yu3'),
    ('有机会', '有机会', 'you3 ji1hui4'),
    ('大家庭', '大家庭', 'da4 jia1ting2'),
    ('上工作', '上工作', 'shang4 gong1zuo4'),
    ('來日本', '来日本', 'lai2 Ri4ben3'),
    ('上任何', '上任何', 'shang4 ren4he2'),
    ('新房子', '新房子', 'xin1 fang2zi5'),
    ('在外面', '在外面', 'zai4 wai4mian4'),
    ('人参加', '人参加', 'ren2 can1jia1'),
    ('穿衣服', '穿衣服', 'chuan1 yi1fu5'),
    ('了事故', '了事故', 'le5 shi4gu4'),
    ('很多時間', '很多时间', 'hen3 duo1 shi2jian1'),
    ('過火車', '过火车', 'guo5 huo3che1'),
    ('讀报紙', '读报纸', 'du2 bao4zhi3'),
]
